//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurssitietokanta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Käyttöoikeudet
    {
        public int Käyttöoikeus_Id { get; set; }
        public string Käytöoikeusnimi { get; set; }
        public string Kuvaus { get; set; }
        public Nullable<int> Rooli_Id { get; set; }
        public Nullable<System.DateTime> Pvm { get; set; }
    
        public virtual Roolit Roolit { get; set; }
    }
}
