//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurssitietokanta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lukukaudet
    {
        public int Lukukausi_Id { get; set; }
        public int Kausinumero_Id { get; set; }
        public int Tutkintoosa_Id { get; set; }
        public int Opintojakson_Id { get; set; }
        public string Päivienlukumäärä { get; set; }
        public string Tuntienmäärä { get; set; }
        public int Toteutustapa_Id { get; set; }
        public int Toteutuskausi_Id { get; set; }
        public Nullable<System.DateTime> Pvm { get; set; }
        public string Klo { get; set; }
        public string Vikkonpäivä { get; set; }
        public Nullable<int> Kieli_Id { get; set; }
        public string AiheOPtilausjärjestely { get; set; }
    
        public virtual Kausiennumerot Kausiennumerot { get; set; }
        public virtual Kielet Kielet { get; set; }
        public virtual Opintojaksot Opintojaksot { get; set; }
        public virtual Toteutuskaudet Toteutuskaudet { get; set; }
        public virtual Toteutustapoja Toteutustapoja { get; set; }
        public virtual Tutkinnonosat Tutkinnonosat { get; set; }
    }
}
