//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurssitietokanta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Opintojaksot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Opintojaksot()
        {
            this.Lukukaudet = new HashSet<Lukukaudet>();
            this.Tutkintokurssit = new HashSet<Tutkintokurssit>();
        }
    
        public int Opintojakson_Id { get; set; }
        public string Opintojaksonnimi { get; set; }
        public int Tutkintoosa_Id { get; set; }
        public int Opettajan_Id { get; set; }
        public string Tavoiteet { get; set; }
        public string Opintokeskinen { get; set; }
        public Nullable<int> Tekininenmateriaali_Id { get; set; }
        public Nullable<int> Opintomateriaali_Id { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Lukukaudet> Lukukaudet { get; set; }
        public virtual Opettajat Opettajat { get; set; }
        public virtual Opintomateriaalit Opintomateriaalit { get; set; }
        public virtual Teknisetmateriaalit Teknisetmateriaalit { get; set; }
        public virtual Tutkinnonosat Tutkinnonosat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tutkintokurssit> Tutkintokurssit { get; set; }
    }
}
