//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurssitietokanta.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class tiimi4Entities1 : DbContext
    {
        public tiimi4Entities1()
            : base("name=tiimi4Entities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Kausiennumerot> Kausiennumerot { get; set; }
        public virtual DbSet<Käyttöoikeudet> Käyttöoikeudet { get; set; }
        public virtual DbSet<Kielet> Kielet { get; set; }
        public virtual DbSet<Kurssimateriaalit> Kurssimateriaalit { get; set; }
        public virtual DbSet<Login> Login { get; set; }
        public virtual DbSet<Lukukaudet> Lukukaudet { get; set; }
        public virtual DbSet<Opettajat> Opettajat { get; set; }
        public virtual DbSet<Opintojaksot> Opintojaksot { get; set; }
        public virtual DbSet<Opintomateriaalit> Opintomateriaalit { get; set; }
        public virtual DbSet<Roolit> Roolit { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Teknisetmateriaalit> Teknisetmateriaalit { get; set; }
        public virtual DbSet<Toteutuskaudet> Toteutuskaudet { get; set; }
        public virtual DbSet<Toteutustapoja> Toteutustapoja { get; set; }
        public virtual DbSet<Tutkinnonosat> Tutkinnonosat { get; set; }
        public virtual DbSet<Tutkinnot> Tutkinnot { get; set; }
        public virtual DbSet<Tutkintoalueet> Tutkintoalueet { get; set; }
        public virtual DbSet<Tutkintokurssit> Tutkintokurssit { get; set; }
        public virtual DbSet<Vastuuopettajat> Vastuuopettajat { get; set; }
        public virtual DbSet<database_firewall_rules> database_firewall_rules { get; set; }
    }
}
