//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurssitietokanta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tutkinnot
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Tutkinnot()
        {
            this.Tutkinnonosat = new HashSet<Tutkinnonosat>();
            this.Tutkintokurssit = new HashSet<Tutkintokurssit>();
            this.Tutkintoalueet = new HashSet<Tutkintoalueet>();
        }
    
        public int Tutkinto_Id { get; set; }
        public string Tutkintonimi { get; set; }
        public Nullable<System.DateTime> Aloitusvuosi { get; set; }
        public Nullable<System.DateTime> Päättymisvuosi { get; set; }
        public string Kesto { get; set; }
        public string OSP { get; set; }
        public string LoginErrorMessage { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tutkinnonosat> Tutkinnonosat { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tutkintokurssit> Tutkintokurssit { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Tutkintoalueet> Tutkintoalueet { get; set; }
    }
}
