//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurssitietokanta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tutkintokurssit
    {
        public int Tutkintokurssi_Id { get; set; }
        public Nullable<int> Tutkinto_Id { get; set; }
        public Nullable<int> Opintojakso_Id { get; set; }
    
        public virtual Opintojaksot Opintojaksot { get; set; }
        public virtual Tutkinnot Tutkinnot { get; set; }
    }
}
