//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace kurssitietokanta.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tutkintoalueet
    {
        public int Tutkintoalue_Id { get; set; }
        public int Tutkinto_Id { get; set; }
        public string Tutkintoaluenimi { get; set; }
    
        public virtual Tutkinnot Tutkinnot { get; set; }
    }
}
